local wk = require("which-key")
wk.setup({
  icons = {
    -- disables icons in pop up
    mappings = false,
    -- If you are using a Nerd Font: set icons.keys to an empty table which will use the
    -- default whick-key.nvim defined Nerd Font icons, otherwise define a string table
    -- keys = false and {} or {
      --   Up = '<Up> ',
      --   Down = '<Down> ',
      --   Left = '<Left> ',
      --   Right = '<Right> ',
      --   C = '<C-…> ',
      --   M = '<M-…> ',
      --   D = '<D-…> ',
      --   S = '<S-…> ',
      --   CR = '<CR> ',
      --   Esc = '<Esc> ',
      --   ScrollWheelDown = '<ScrollWheelDown> ',
      --   ScrollWheelUp = '<ScrollWheelUp> ',
      --   NL = '<NL> ',
      --   BS = '<BS> ',
      --   Space = '<Space> ',
      --   Tab = '<Tab> ',
      --   F1 = '<F1>',
      --   F2 = '<F2>',
      --   F3 = '<F3>',
      --   F4 = '<F4>',
      --   F5 = '<F5>',
      --   F6 = '<F6>',
      --   F7 = '<F7>',
      --   F8 = '<F8>',
      --   F9 = '<F9>',
      --   F10 = '<F10>',
      --   F11 = '<F11>',
      --   F12 = '<F12>',
      -- },
    },
  }
)
wk.add({
  -- { "<leader>d", desc = "duplicate file" },
  -- { "<leader>p", desc = "toggle theme" },
  -- { "<leader>u", desc = "open url" },
  -- { "<leader>z", desc = "floating terminal" },
  -- { "<leader>f", desc = "fzf" },
  -- { "<leader>g", desc = "grep" },
  -- { "<leader>G", desc = "grep under cursor" },
  -- { "<leader>x", desc = "chmod +x" },
  { "<leader>t", desc = "toggle term" },
  { "<leader>e", desc = "toggle file explorer" },
  -- { "<leader>R", desc = "reload config" },
  -- { "<leader>vs", desc = "vsplit next buf" },
  -- { "<leader>w", desc = "write" },
  -- { "<leader>W", desc = "toggle wrap" },
  -- { "<leader>q", desc = "close buf" },
  -- { "<leader>Q", desc = "close buf!" },
  -- { "<leader>U", desc = "close ALL buf" },
  -- { "<leader>nn", desc = "toggle relative nums" },
  -- { "<leader>H", desc = "htop terminal" },
  -- { "<leader>T", desc = "git status" },
  -- { "<leader>F", desc = "fzf opts" },
})
